kind: PersistentVolume
apiVersion: v1
metadata:
  name: ucd-drivers-pv
  labels:
    type: local-storage
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/export/ICP3/ucddrivers"
    server: 192.168.33.24 
