kind: PersistentVolume
apiVersion: v1
metadata:
  name: ucd-pv
  labels:
    type: local-storage
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/export/ICP3/ucd"
    server: 192.168.24.33
